"""Storage: Postgres (records, vectors, RBAC, versions) + Neo4j (relationships).

The bridge lives here. A chunk gets one UUID, generated by Postgres, and that same
UUID becomes the id of a (:Chunk) node in Neo4j. Every entity the extractor found
in that chunk is wired to the Chunk node with a MENTIONS edge. That is what makes
the two stores one system:

    a vector hit  -> chunk id -> (:Chunk) -> MENTIONS -> entities -> traverse
    a graph hit   -> entity   -> MENTIONS -> (:Chunk) -> chunk id -> the exact text

Neither store can do that alone, and it is the whole argument of the project.
"""

import json
import uuid
from contextlib import contextmanager
from typing import Any, Iterator

import psycopg
from neo4j import Driver, GraphDatabase
from pgvector.psycopg import register_vector
from psycopg.rows import dict_row

from meridian.config import settings
from meridian.ontology import Extraction

# ---------------------------------------------------------------------------
# Postgres
# ---------------------------------------------------------------------------


@contextmanager
def pg() -> Iterator[psycopg.Connection]:
    conn = psycopg.connect(settings().postgres_dsn, row_factory=dict_row)
    try:
        register_vector(conn)
        yield conn
        conn.commit()
    except Exception:
        conn.rollback()
        raise
    finally:
        conn.close()


def upsert_document(
    conn: psycopg.Connection,
    *,
    title: str,
    doc_type: str,
    raw_text: str,
    content_hash: str,
    sensitivity: int = 2,
    source_uri: str | None = None,
    metadata: dict[str, Any] | None = None,
) -> tuple[uuid.UUID, bool]:
    """Insert a document, or return the existing one if the bytes were seen before.

    Returns (document_id, is_new). Dedupe is on content_hash, so re-uploading the
    same board deck under a different filename does not double every entity in the
    graph. Idempotent ingestion is not a nicety here — the extractor is expensive
    and the graph is append-only.
    """
    row = conn.execute(
        """
        INSERT INTO document (title, doc_type, source_uri, raw_text, content_hash,
                              sensitivity, metadata)
        VALUES (%s, %s, %s, %s, %s, %s, %s)
        ON CONFLICT (content_hash) DO NOTHING
        RETURNING id
        """,
        (title, doc_type, source_uri, raw_text, content_hash, sensitivity,
         json.dumps(metadata or {})),
    ).fetchone()

    if row:
        return row["id"], True

    existing = conn.execute(
        "SELECT id FROM document WHERE content_hash = %s", (content_hash,)
    ).fetchone()
    return existing["id"], False


def insert_chunks(
    conn: psycopg.Connection,
    *,
    document_id: uuid.UUID,
    texts: list[str],
    embeddings: list[list[float]],
    sensitivity: int,
) -> list[uuid.UUID]:
    """Write chunks + embeddings. Postgres mints the UUIDs the graph will reuse."""
    ids: list[uuid.UUID] = []
    for ordinal, (text, vector) in enumerate(zip(texts, embeddings, strict=True)):
        row = conn.execute(
            """
            INSERT INTO chunk (document_id, ordinal, text, sensitivity, embedding)
            VALUES (%s, %s, %s, %s, %s)
            RETURNING id
            """,
            (document_id, ordinal, text, sensitivity, vector),
        ).fetchone()
        ids.append(row["id"])
    return ids


def queue_proposals(
    conn: psycopg.Connection,
    *,
    document_id: uuid.UUID,
    chunk_id: uuid.UUID,
    extraction: Extraction,
) -> int:
    """Park an extraction in the approval queue. Nothing reaches the graph yet.

    The evidence quote the extractor was forced to attach travels with the proposal,
    so the founder reviewing it can see the sentence the claim rests on rather than
    taking the model's word for it.
    """
    count = 0

    for entity in extraction.entities:
        conn.execute(
            """
            INSERT INTO proposed_change (document_id, kind, payload, evidence, confidence)
            VALUES (%s, 'add_entity', %s, %s, %s)
            """,
            (
                document_id,
                json.dumps({
                    "name": entity.name,
                    "type": entity.type.value,
                    "attributes": entity.attributes,
                    "chunk_id": str(chunk_id),
                }),
                json.dumps([str(chunk_id)]),
                1.0,  # an entity that appears in the text is not a judgment call
            ),
        )
        count += 1

    for rel in extraction.relationships:
        conn.execute(
            """
            INSERT INTO proposed_change (document_id, kind, payload, evidence, confidence)
            VALUES (%s, 'add_relationship', %s, %s, %s)
            """,
            (
                document_id,
                json.dumps({
                    "source": rel.source,
                    "type": rel.type.value,
                    "target": rel.target,
                    "quote": rel.evidence,
                    "chunk_id": str(chunk_id),
                }),
                json.dumps([str(chunk_id)]),
                rel.confidence,
            ),
        )
        count += 1

    return count


def pending(conn: psycopg.Connection, limit: int = 50) -> list[dict[str, Any]]:
    """The founder's review queue, lowest-confidence first — the ones most worth a human."""
    return conn.execute(
        """
        SELECT id, kind, payload, confidence, created_at
        FROM proposed_change
        WHERE status = 'pending'
        ORDER BY confidence ASC, created_at ASC
        LIMIT %s
        """,
        (limit,),
    ).fetchall()


# ---------------------------------------------------------------------------
# Neo4j
# ---------------------------------------------------------------------------


def neo() -> Driver:
    cfg = settings()
    return GraphDatabase.driver(cfg.neo4j_uri, auth=(cfg.neo4j_user, cfg.neo4j_password))


CONSTRAINTS = [
    "CREATE CONSTRAINT chunk_id IF NOT EXISTS FOR (c:Chunk) REQUIRE c.id IS UNIQUE",
    # Entities are identified by (name, type). Two people called "Raj" collapse into
    # one node — that is entity resolution by exact name, and it is the honest
    # limitation of this prototype. Real resolution (aliases, "Raj" vs "Rajesh Kumar",
    # embedding-similarity blocking) is scoped as future work; say so in the report
    # rather than pretending the problem does not exist.
    "CREATE CONSTRAINT entity_key IF NOT EXISTS FOR (e:Entity) REQUIRE (e.name, e.type) IS UNIQUE",
]


def ensure_constraints(driver: Driver) -> None:
    with driver.session() as session:
        for stmt in CONSTRAINTS:
            session.run(stmt)


def upsert_chunk_node(driver: Driver, *, chunk_id: uuid.UUID, document_id: uuid.UUID,
                      ordinal: int, sensitivity: int) -> None:
    """The graph half of the bridge. Text stays in Postgres; only the handle lives here."""
    with driver.session() as session:
        session.run(
            """
            MERGE (c:Chunk {id: $id})
            SET c.document_id = $document_id,
                c.ordinal     = $ordinal,
                c.sensitivity = $sensitivity
            """,
            id=str(chunk_id),
            document_id=str(document_id),
            ordinal=ordinal,
            sensitivity=sensitivity,
        )


def apply_entity(driver: Driver, payload: dict[str, Any]) -> None:
    """Commit an approved entity, and wire it to the chunk that mentions it."""
    with driver.session() as session:
        session.run(
            """
            MERGE (e:Entity {name: $name, type: $type})
            SET e += $attributes
            WITH e
            MATCH (c:Chunk {id: $chunk_id})
            MERGE (c)-[:MENTIONS]->(e)
            """,
            name=payload["name"],
            type=payload["type"],
            attributes=payload.get("attributes", {}),
            chunk_id=payload["chunk_id"],
        )


def apply_relationship(driver: Driver, payload: dict[str, Any]) -> None:
    """Commit an approved relationship.

    The edge type is interpolated into the Cypher string because Neo4j does not
    accept a parameterised relationship type. That is an injection surface, so the
    value is checked against the RelationType enum before it gets here — never
    relax that check, and never let an unvalidated string reach this function.
    """
    rel_type = payload["type"]
    from meridian.ontology import RelationType

    if rel_type not in RelationType.__members__.values():
        raise ValueError(f"Refusing to write unknown relationship type: {rel_type!r}")

    with driver.session() as session:
        session.run(
            f"""
            MATCH (s:Entity {{name: $source}})
            MATCH (t:Entity {{name: $target}})
            MERGE (s)-[r:{rel_type}]->(t)
            SET r.quote = $quote, r.chunk_id = $chunk_id
            """,
            source=payload["source"],
            target=payload["target"],
            quote=payload.get("quote", ""),
            chunk_id=payload["chunk_id"],
        )


def approve(conn: psycopg.Connection, driver: Driver, change_id: uuid.UUID,
            reviewer_id: uuid.UUID | None = None) -> None:
    """The only path by which anything reaches the graph.

    Postgres and Neo4j have no shared transaction, so we commit to the graph first
    and mark the row approved second. If the process dies between the two, the row
    stays 'pending' and gets re-applied — the graph writes are MERGE, so replaying
    is a no-op. The reverse order would risk a row marked approved whose edge was
    never written, which is the failure we cannot detect later.
    """
    row = conn.execute(
        "SELECT kind, payload FROM proposed_change WHERE id = %s AND status = 'pending'",
        (change_id,),
    ).fetchone()
    if not row:
        raise ValueError(f"No pending change {change_id}")

    if row["kind"] == "add_entity":
        apply_entity(driver, row["payload"])
    elif row["kind"] == "add_relationship":
        apply_relationship(driver, row["payload"])
    else:
        raise ValueError(f"Unknown change kind: {row['kind']}")

    conn.execute(
        """
        UPDATE proposed_change
        SET status = 'approved', reviewed_by = %s, reviewed_at = now()
        WHERE id = %s
        """,
        (reviewer_id, change_id),
    )

    conn.execute(
        """
        INSERT INTO node_version (node_id, node_label, version, properties, change_reason, created_by)
        VALUES (%s, %s,
                COALESCE((SELECT MAX(version) + 1 FROM node_version WHERE node_id = %s), 1),
                %s, 'approved from extraction', %s)
        """,
        (change_id, row["kind"], change_id, json.dumps(row["payload"]), reviewer_id),
    )
