"use client";

import { useEffect, useState } from "react";
import { ClipboardList } from "lucide-react";
import { PageHeader } from "@/components/ui/page-header";
import { Card } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { LoadFailed, asApiError } from "@/components/ui/load-failed";
import type { ApiError } from "@/lib/http";
import { cn } from "@/lib/utils";
import { meetingsApi, type Meeting } from "@/lib/meetings";
import { commitmentsApi, todayLocal, type Commitment } from "@/lib/commitments";
import { decisionsApi, type Decision } from "@/lib/decisions";
import { agendaApi, type AgendaItem } from "@/lib/agenda";
import { packsApi, type BoardPack } from "@/lib/packs";
import {
  prepReadiness,
  prepSignals,
  suggestAgenda,
  type PrepSignal,
  type AgendaSuggestion,
} from "@/lib/prep";

/**
 * Prepare Meeting.
 *
 * Follows the five-step prototype — Gathering, Analysis, Agenda, Board Pack, Readiness —
 * and departs from it in three places, each deliberate:
 *
 * 1. **No "Generated by AI" pack sections.** The prototype drafts an Executive Summary
 *    and a Financial Performance section and labels them generated. A generated section
 *    carries no source quote, which is the one thing `rules.md` §2 forbids surfacing.
 * 2. **No Finance / HR / Product / CRM sources.** Those modules do not exist in this
 *    product. Rendering them would invent an integration layer that is P5/P7 work.
 * 3. **Readiness in counts, not percentages.** See `lib/prep.ts` — 90% agenda and 40%
 *    approvals have no denominators.
 *
 * Everything shown here is a row someone can open.
 *
 * The measure is narrower than the rest of the application (`max-w-3xl`), matching the
 * prototype: this is a page read top to bottom in order, not a dashboard scanned in
 * parallel, and a long line is harder to resume after looking away.
 *
 * **Read-only for now.** Adding a suggestion to the agenda is a write, and `agendaApi`
 * exposes only `list` and `get` — the POST exists in the API and has no client. That is
 * the next commit, kept separate so this one is verifiable on its own.
 */

const STEPS = ["Gathering", "Analysis", "Agenda", "Board pack", "Readiness"] as const;

type Loaded = {
  meeting: Meeting;
  commitments: Commitment[];
  decisions: Decision[];
  agenda: AgendaItem[];
  packs: BoardPack[];
};

export default function PreparePage() {
  const [data, setData] = useState<Loaded | null>(null);
  const [error, setError] = useState<ApiError | null>(null);
  const today = todayLocal();

  useEffect(() => {
    let stale = false;

    (async () => {
      const meetings = await meetingsApi.list();
      // The meeting being prepared is the next one not yet held. Meetings with no
      // scheduled start sort last: an unscheduled meeting cannot be "next".
      const upcoming = meetings
        .filter((m) => m.status === "draft" || m.status === "scheduled")
        .sort((a, b) => (a.scheduled_start ?? "").localeCompare(b.scheduled_start ?? ""));
      const meeting = upcoming[0] ?? meetings[0];
      if (!meeting) {
        if (!stale) setData(null);
        return;
      }

      const [commitments, decisions, agenda, packs] = await Promise.all([
        commitmentsApi.list(),
        decisionsApi.listForMeetings(meetings.map((m) => m.id)),
        agendaApi.list(meeting.id),
        packsApi.list({ meeting_id: meeting.id }),
      ]);

      if (stale) return;
      setData({ meeting, commitments, decisions, agenda, packs });
    })().catch((e) => {
      if (!stale) setError(asApiError(e));
    });

    return () => {
      stale = true;
    };
  }, []);

  if (error) {
    return (
      <div className="mx-auto max-w-3xl p-8">
        <LoadFailed what="Meeting preparation" error={error} />
      </div>
    );
  }

  const signals = data ? prepSignals(data.commitments, data.decisions, today) : null;
  const suggestions = data
    ? suggestAgenda(data.commitments, data.decisions, data.agenda, today)
    : null;
  const readiness = data
    ? prepReadiness(data.agenda, data.packs, data.commitments, data.decisions, today)
    : null;

  return (
    <div className="mx-auto max-w-3xl p-8">
      <PageHeader
        title="Prepare meeting"
        description={
          data
            ? `${data.meeting.title} — assembled from what the board has not finished.`
            : "Assembled from what the board has not finished."
        }
        icon={<ClipboardList />}
      />

      <Stepper current={data ? 4 : 0} />

      <Section
        step={1}
        title="Gathering"
        note="What was read to build this page. Each is a live request scoped to your clearance."
      >
        {data === null ? (
          <SkeletonRows n={4} />
        ) : (
          <dl className="grid grid-cols-2 gap-x-6 gap-y-2 text-sm">
            <Fact label="Commitments" value={data.commitments.length} />
            <Fact label="Decisions" value={data.decisions.length} />
            <Fact label="Agenda items" value={data.agenda.length} />
            <Fact label="Board packs" value={data.packs.length} />
          </dl>
        )}
      </Section>

      <Section
        step={2}
        title="Analysis"
        note="Statements of fact, one per row. Nothing is summarised across rows, because a summary needs data this product does not hold."
      >
        {signals === null ? (
          <SkeletonRows n={3} />
        ) : signals.length === 0 ? (
          <Empty>Nothing is outstanding. No open commitments, no undecided proposals.</Empty>
        ) : (
          <ul className="space-y-2">
            {signals.map((s) => (
              <SignalRow key={s.id} signal={s} />
            ))}
          </ul>
        )}
      </Section>

      <Section
        step={3}
        title="Agenda"
        note="Proposed from unfinished business. Anything already on the agenda is left out."
      >
        {suggestions === null ? (
          <SkeletonRows n={3} />
        ) : suggestions.length === 0 ? (
          <Empty>
            Nothing to propose — every open item is already on the agenda, or there are none.
          </Empty>
        ) : (
          <ul className="space-y-2">
            {suggestions.map((s) => (
              <SuggestionRow key={s.id} suggestion={s} />
            ))}
          </ul>
        )}
      </Section>

      <Section
        step={4}
        title="Board pack"
        note="Assembled from documents already in the workspace. Items are filtered at your clearance before they reach this page."
      >
        {data === null ? (
          <SkeletonRows n={2} />
        ) : data.packs.length === 0 ? (
          <Empty>No pack exists for this meeting yet.</Empty>
        ) : (
          <ul className="space-y-2">
            {data.packs.map((p) => (
              <li
                key={p.id}
                className="flex items-center justify-between rounded-[12px] border border-border px-4 py-3"
              >
                <div className="min-w-0">
                  <p className="truncate text-sm font-medium text-foreground">{p.title}</p>
                  <p className="text-xs text-muted-foreground">
                    Version {p.version_no} · {p.items.length}{" "}
                    {p.items.length === 1 ? "item" : "items"}
                  </p>
                </div>
                <Badge tone={p.status === "published" ? "success" : "neutral"}>{p.status}</Badge>
              </li>
            ))}
          </ul>
        )}
      </Section>

      <Section
        step={5}
        title="Readiness"
        note="Counts, not percentages. There is no defined total for a complete agenda, so a percentage would be a measurement nobody took."
      >
        {readiness === null ? (
          <SkeletonRows n={3} />
        ) : (
          <dl className="grid grid-cols-2 gap-x-6 gap-y-2 text-sm">
            <Fact label="Agenda items" value={readiness.agendaItems} />
            <Fact
              label="Published pack items"
              value={readiness.packItems}
              // Null is not zero: zero would claim the pack is empty, when the truth is
              // that no pack is published to count.
              nullNote="no published pack"
            />
            <Fact label="Open commitments" value={readiness.openCommitments} />
            <Fact
              label="Overdue commitments"
              value={readiness.overdueCommitments}
              tone={readiness.overdueCommitments > 0 ? "critical" : undefined}
            />
            <Fact label="Undecided proposals" value={readiness.openDecisions} />
          </dl>
        )}
      </Section>
    </div>
  );
}

function Stepper({ current }: { current: number }) {
  return (
    <ol className="mt-6 flex items-center gap-2" aria-label="Preparation steps">
      {STEPS.map((label, i) => {
        const done = i < current;
        return (
          <li key={label} className="flex flex-1 items-center gap-2">
            <span
              className={cn(
                "grid size-5 shrink-0 place-items-center rounded-full text-[11px] font-semibold",
                done
                  ? "bg-accent text-accent-foreground"
                  : "border border-border text-subtle-foreground",
              )}
              aria-hidden
            >
              {i + 1}
            </span>
            <span
              className={cn(
                "truncate text-xs",
                done ? "text-foreground" : "text-muted-foreground",
              )}
            >
              {label}
            </span>
            {i < STEPS.length - 1 && <span className="h-px flex-1 bg-border" aria-hidden />}
          </li>
        );
      })}
    </ol>
  );
}

function Section({
  step,
  title,
  note,
  children,
}: {
  step: number;
  title: string;
  note: string;
  children: React.ReactNode;
}) {
  return (
    <Card className="mt-6 p-6">
      <div className="flex items-baseline gap-2">
        <span className="text-xs font-medium tabular-nums text-subtle-foreground">{step}</span>
        <h2 className="text-sm font-semibold text-foreground">{title}</h2>
      </div>
      <p className="mt-1 text-xs text-muted-foreground">{note}</p>
      <div className="mt-4">{children}</div>
    </Card>
  );
}

function SignalRow({ signal }: { signal: PrepSignal }) {
  return (
    <li className="rounded-[12px] border border-border px-4 py-3">
      <p className="text-sm text-foreground">{signal.statement}</p>
      <p className="mt-1.5 text-xs text-muted-foreground">
        {/* The source is the point of the row, not an ornament on it. */}
        Source: {signal.source.label}
      </p>
    </li>
  );
}

function SuggestionRow({ suggestion }: { suggestion: AgendaSuggestion }) {
  return (
    <li className="rounded-[12px] border border-border px-4 py-3">
      <p className="text-sm font-medium text-foreground">{suggestion.title}</p>
      <p className="mt-1 text-xs text-muted-foreground">{suggestion.reason}</p>
      <p className="mt-1.5 text-xs text-muted-foreground">Source: {suggestion.source.label}</p>
    </li>
  );
}

function Fact({
  label,
  value,
  tone,
  nullNote,
}: {
  label: string;
  value: number | null;
  tone?: "critical";
  nullNote?: string;
}) {
  return (
    <>
      <dt className="text-muted-foreground">{label}</dt>
      <dd
        className={cn(
          "text-right tabular-nums",
          tone === "critical" ? "font-medium text-danger-emphasis" : "text-foreground",
        )}
      >
        {value === null ? (
          <span className="text-subtle-foreground" title={nullNote}>
            —
          </span>
        ) : (
          value
        )}
      </dd>
    </>
  );
}

function Empty({ children }: { children: React.ReactNode }) {
  return <p className="text-sm text-muted-foreground">{children}</p>;
}

function SkeletonRows({ n }: { n: number }) {
  return (
    <div className="space-y-2">
      {Array.from({ length: n }).map((_, i) => (
        <div key={i} className="h-9 rounded-[12px] bg-surface-sunken" />
      ))}
    </div>
  );
}
