"use client";

import { useEffect, useState } from "react";
import { ClipboardList } from "lucide-react";
import { PageHeader } from "@/components/ui/page-header";
import { Card } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { LoadFailed, asApiError } from "@/components/ui/load-failed";
import { ApiError } from "@/lib/http";
import { serverMessage } from "@/lib/error-text";
import { cn } from "@/lib/utils";
import { meetingsApi, type Meeting } from "@/lib/meetings";
import { commitmentsApi, todayLocal, type Commitment } from "@/lib/commitments";
import { decisionsApi, type Decision } from "@/lib/decisions";
import { agendaApi, type AgendaItem } from "@/lib/agenda";
import { packsApi, type BoardPack } from "@/lib/packs";
import {
  nextMeetingToPrepare,
  prepReadiness,
  prepSignals,
  sourceHref,
  suggestAgenda,
  type PrepSignal,
  type PrepSource,
  type AgendaSuggestion,
} from "@/lib/prep";
import { Stages } from "./stages";

/**
 * Prepare Meeting.
 *
 * Follows the five-step prototype — Gathering, Analysis, Agenda, Board Pack, Readiness —
 * and departs from it in three places, each deliberate:
 *
 * 1. **No "Generated by AI" pack sections.** The prototype drafts an Executive Summary
 *    and a Financial Performance section and labels them generated. A generated section
 *    carries no source quote, which is the one thing `rules.md` §2 forbids surfacing.
 * 2. **No Finance / HR / Product / CRM sources.** Those modules do not exist in this
 *    product. Rendering them would invent an integration layer that is P5/P7 work.
 * 3. **Readiness in counts, not percentages.** See `lib/prep.ts` — 90% agenda and 40%
 *    approvals have no denominators.
 *
 * Everything shown here is a row someone can open.
 *
 * The measure is narrower than the rest of the application (`max-w-3xl`), matching the
 * prototype: this is a page read top to bottom in order, not a dashboard scanned in
 * parallel, and a long line is harder to resume after looking away.
 *
 * **One write.** A suggestion can be added to the agenda; nothing else on this page
 * changes anything. Adding is per row rather than "add all", because each item is a
 * separate judgement and a bulk button invites accepting the fourth without reading it.
 * The suggestion then disappears from the list — `suggestAgenda` excludes what is
 * already on the agenda, so the list shortening is the confirmation, and there is no
 * success toast asserting something the screen has already shown.
 */

type Loaded = {
  meeting: Meeting;
  commitments: Commitment[];
  decisions: Decision[];
  agenda: AgendaItem[];
  packs: BoardPack[];
};

export default function PreparePage() {
  const [data, setData] = useState<Loaded | null>(null);
  const [error, setError] = useState<ApiError | null>(null);
  const today = todayLocal();

  useEffect(() => {
    let stale = false;

    (async () => {
      const meetings = await meetingsApi.list();
      const meeting = nextMeetingToPrepare(meetings);
      if (!meeting) {
        if (!stale) setData(null);
        return;
      }

      const [commitments, decisions, agenda, packs] = await Promise.all([
        commitmentsApi.list(),
        decisionsApi.listForMeetings(meetings.map((m) => m.id)),
        agendaApi.list(meeting.id),
        packsApi.list({ meeting_id: meeting.id }),
      ]);

      if (stale) return;
      setData({ meeting, commitments, decisions, agenda, packs });
    })().catch((e) => {
      if (!stale) setError(asApiError(e));
    });

    return () => {
      stale = true;
    };
  }, []);

  /**
   * Puts a suggestion on the agenda.
   *
   * The created item is appended to local state rather than the page refetching. The
   * server's response IS the record — it carries the real id, position and version —
   * so re-reading would only confirm what it already told us, and would race with a
   * second add. `suggestAgenda` then drops the suggestion on the next render because
   * its title now matches an agenda item.
   *
   * Errors are deliberately re-thrown: the row that was clicked reports its own
   * failure, and swallowing here would leave the reader with a button that did nothing
   * and said nothing.
   */
  async function addToAgenda(suggestion: AgendaSuggestion) {
    if (!data) return;
    const created = await agendaApi.create({
      meeting_id: data.meeting.id,
      title: suggestion.title,
      // The reason is stored as the description so the agenda item carries the
      // provenance of its own existence. Without it, "why is this here?" is
      // answerable on this page and nowhere else.
      description: suggestion.reason,
    });
    setData((prev) => (prev ? { ...prev, agenda: [...prev.agenda, created] } : prev));
  }

  if (error) {
    return (
      <div className="mx-auto max-w-3xl p-8">
        <LoadFailed what="Meeting preparation" error={error} />
      </div>
    );
  }

  const signals = data ? prepSignals(data.commitments, data.decisions, today) : null;
  const suggestions = data
    ? suggestAgenda(data.commitments, data.decisions, data.agenda, today)
    : null;
  const readiness = data
    ? prepReadiness(data.agenda, data.packs, data.commitments, data.decisions, today)
    : null;

  return (
    <div className="mx-auto max-w-3xl p-8">
      <PageHeader
        title="Prepare meeting"
        description={
          data
            ? `${data.meeting.title} — assembled from what the board has not finished.`
            : "Assembled from what the board has not finished."
        }
        icon={<ClipboardList />}
      />

      <Stages />

      <Section
        id="gathering"
        step={1}
        title="Gathering"
        note="What was read to build this page. Each is a live request scoped to your clearance."
      >
        {data === null ? (
          <SkeletonRows n={4} />
        ) : (
          <dl className="grid grid-cols-2 gap-x-6 gap-y-2 text-sm">
            <Fact label="Commitments" value={data.commitments.length} />
            <Fact label="Decisions" value={data.decisions.length} />
            <Fact label="Agenda items" value={data.agenda.length} />
            <Fact label="Board packs" value={data.packs.length} />
          </dl>
        )}
      </Section>

      <Section
        id="analysis"
        step={2}
        title="Analysis"
        note="Statements of fact, one per row. Nothing is summarised across rows, because a summary needs data this product does not hold."
      >
        {signals === null ? (
          <SkeletonRows n={3} />
        ) : signals.length === 0 ? (
          <Empty>Nothing is outstanding. No open commitments, no undecided proposals.</Empty>
        ) : (
          <ul className="space-y-2">
            {signals.map((s) => (
              <SignalRow key={s.id} signal={s} />
            ))}
          </ul>
        )}
      </Section>

      <Section
        id="agenda"
        step={3}
        title="Agenda"
        note="Proposed from unfinished business. Anything already on the agenda is left out."
      >
        {suggestions === null ? (
          <SkeletonRows n={3} />
        ) : suggestions.length === 0 ? (
          <Empty>
            Nothing to propose — every open item is already on the agenda, or there are none.
          </Empty>
        ) : (
          <ul className="space-y-2">
            {suggestions.map((s) => (
              <SuggestionRow key={s.id} suggestion={s} onAdd={addToAgenda} />
            ))}
          </ul>
        )}
      </Section>

      <Section
        id="board-pack"
        step={4}
        title="Board pack"
        note="Assembled from documents already in the workspace. Items are filtered at your clearance before they reach this page."
      >
        {data === null ? (
          <SkeletonRows n={2} />
        ) : data.packs.length === 0 ? (
          <Empty>No pack exists for this meeting yet.</Empty>
        ) : (
          <ul className="space-y-2">
            {data.packs.map((p) => (
              <li
                key={p.id}
                className="flex items-center justify-between rounded-[12px] border border-border px-4 py-3"
              >
                <div className="min-w-0">
                  <p className="truncate text-sm font-medium text-foreground">{p.title}</p>
                  <p className="text-xs text-muted-foreground">
                    Version {p.version_no} · {p.items.length}{" "}
                    {p.items.length === 1 ? "item" : "items"}
                  </p>
                </div>
                <Badge tone={p.status === "published" ? "success" : "neutral"}>{p.status}</Badge>
              </li>
            ))}
          </ul>
        )}
      </Section>

      <Section
        id="readiness"
        step={5}
        title="Readiness"
        note="Counts, not percentages. There is no defined total for a complete agenda, so a percentage would be a measurement nobody took."
      >
        {readiness === null ? (
          <SkeletonRows n={3} />
        ) : (
          <dl className="grid grid-cols-2 gap-x-6 gap-y-2 text-sm">
            <Fact label="Agenda items" value={readiness.agendaItems} />
            <Fact
              label="Published pack items"
              value={readiness.packItems}
              // Null is not zero: zero would claim the pack is empty, when the truth is
              // that no pack is published to count.
              nullNote="no published pack"
            />
            <Fact label="Open commitments" value={readiness.openCommitments} />
            <Fact
              label="Overdue commitments"
              value={readiness.overdueCommitments}
              tone={readiness.overdueCommitments > 0 ? "critical" : undefined}
            />
            <Fact label="Undecided proposals" value={readiness.openDecisions} />
          </dl>
        )}
      </Section>
    </div>
  );
}


function Section({
  id,
  step,
  title,
  note,
  children,
}: {
  id: string;
  step: number;
  title: string;
  note: string;
  children: React.ReactNode;
}) {
  return (
    <Card id={id} className="mt-6 scroll-mt-8 p-6">
      <div className="flex items-baseline gap-2">
        <span className="text-xs font-medium tabular-nums text-subtle-foreground">{step}</span>
        <h2 className="text-sm font-semibold text-foreground">{title}</h2>
      </div>
      <p className="mt-1 text-xs text-muted-foreground">{note}</p>
      <div className="mt-4">{children}</div>
    </Card>
  );
}

/**
 * The source of a derived claim, made checkable.
 *
 * The source is the point of the row, not an ornament on it — so where the product can
 * resolve the id, this is a link to the record itself. Where it cannot, the id is
 * printed as text rather than dressed as a link that would 404. A reader who cannot
 * reach the record can at least search for it.
 */
function SourceLine({ source }: { source: PrepSource }) {
  const href = sourceHref(source);

  return (
    <p className="mt-1.5 text-xs text-muted-foreground">
      Source:{" "}
      {href ? (
        <a
          href={href}
          className="text-accent-emphasis underline decoration-accent-border underline-offset-2 transition-colors hover:decoration-accent focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-focus"
        >
          {source.label}
        </a>
      ) : (
        <>
          {source.label}{" "}
          <span className="font-mono text-subtle-foreground" title="No surface resolves this id yet">
            {source.id}
          </span>
        </>
      )}
    </p>
  );
}

function SignalRow({ signal }: { signal: PrepSignal }) {
  return (
    <li className="rounded-[12px] border border-border px-4 py-3">
      <p className="text-sm text-foreground">{signal.statement}</p>
      <SourceLine source={signal.source} />
    </li>
  );
}

/**
 * A suggestion, and the one action this page takes.
 *
 * Adding is per row rather than "add all": each item is a separate judgement, and a
 * bulk button would encourage accepting four suggestions without reading the fourth.
 *
 * Failure is reported **on the row that failed**, not as a page-level banner. Three of
 * the four items may succeed, and a banner would make the reader guess which.
 */
function SuggestionRow({
  suggestion,
  onAdd,
}: {
  suggestion: AgendaSuggestion;
  onAdd: (s: AgendaSuggestion) => Promise<void>;
}) {
  const [busy, setBusy] = useState(false);
  const [failed, setFailed] = useState<string | null>(null);

  async function add() {
    setBusy(true);
    setFailed(null);
    try {
      await onAdd(suggestion);
      // No success state: the row leaves the list, because the suggestion is now on
      // the agenda and `suggestAgenda` excludes what is already there. The list
      // shortening IS the confirmation.
    } catch (e) {
      setFailed(
        e instanceof ApiError
          ? e.isUnretryableConflict
            ? "The agenda is locked — the meeting has already started."
            : serverMessage(e)
          : "Could not reach the server.",
      );
      setBusy(false);
    }
  }

  return (
    <li className="rounded-[12px] border border-border px-4 py-3">
      <div className="flex items-start justify-between gap-4">
        <div className="min-w-0">
          <p className="text-sm font-medium text-foreground">{suggestion.title}</p>
          <p className="mt-1 text-xs text-muted-foreground">{suggestion.reason}</p>
          <SourceLine source={suggestion.source} />
        </div>
        <Button variant="secondary" size="sm" onClick={add} loading={busy} className="shrink-0">
          Add to agenda
        </Button>
      </div>
      {failed && (
        <p role="alert" className="mt-2 text-xs text-danger-emphasis">
          {failed}
        </p>
      )}
    </li>
  );
}

function Fact({
  label,
  value,
  tone,
  nullNote,
}: {
  label: string;
  value: number | null;
  tone?: "critical";
  nullNote?: string;
}) {
  return (
    <>
      <dt className="text-muted-foreground">{label}</dt>
      <dd
        className={cn(
          "text-right tabular-nums",
          tone === "critical" ? "font-medium text-danger-emphasis" : "text-foreground",
        )}
      >
        {value === null ? (
          <span className="text-subtle-foreground" title={nullNote}>
            —
          </span>
        ) : (
          value
        )}
      </dd>
    </>
  );
}

function Empty({ children }: { children: React.ReactNode }) {
  return <p className="text-sm text-muted-foreground">{children}</p>;
}

function SkeletonRows({ n }: { n: number }) {
  return (
    <div className="space-y-2">
      {Array.from({ length: n }).map((_, i) => (
        <div key={i} className="h-9 rounded-[12px] bg-surface-sunken" />
      ))}
    </div>
  );
}
