"""Storage: Postgres (records, vectors, RBAC, versions) + Neo4j (relationships).

The bridge lives here. A chunk gets one UUID, generated by Postgres, and that same
UUID becomes the id of a (:Chunk) node in Neo4j. Every entity the extractor found
in that chunk is wired to the Chunk node with a MENTIONS edge. That is what makes
the two stores one system:

    a vector hit  -> chunk id -> (:Chunk) -> MENTIONS -> entities -> traverse
    a graph hit   -> entity   -> MENTIONS -> (:Chunk) -> chunk id -> the exact text

Neither store can do that alone, and it is the whole argument of the project.
"""

import json
import uuid
from contextlib import contextmanager
from typing import Any, Iterator

import psycopg
from neo4j import Driver, GraphDatabase
from pgvector.psycopg import register_vector
from psycopg.rows import dict_row

from callosum.config import settings

# ---------------------------------------------------------------------------
# Postgres
# ---------------------------------------------------------------------------


@contextmanager
def pg() -> Iterator[psycopg.Connection]:
    conn = psycopg.connect(settings().postgres_dsn, row_factory=dict_row)
    try:
        register_vector(conn)
        yield conn
        conn.commit()
    except Exception:
        conn.rollback()
        raise
    finally:
        conn.close()


def upsert_document(
    conn: psycopg.Connection,
    *,
    title: str,
    doc_type: str,
    raw_text: str,
    content_hash: str,
    sensitivity: int = 2,
    source_uri: str | None = None,
    metadata: dict[str, Any] | None = None,
) -> tuple[uuid.UUID, bool]:
    """Insert a document, or return the existing one if the bytes were seen before.

    Returns (document_id, is_new). Dedupe is on content_hash, so re-uploading the
    same board deck under a different filename does not double every entity in the
    graph. Idempotent ingestion is not a nicety here — the extractor is expensive
    and the graph is append-only.
    """
    row = conn.execute(
        """
        INSERT INTO document (title, doc_type, source_uri, raw_text, content_hash,
                              sensitivity, metadata)
        VALUES (%s, %s, %s, %s, %s, %s, %s)
        ON CONFLICT (content_hash) DO NOTHING
        RETURNING id
        """,
        (title, doc_type, source_uri, raw_text, content_hash, sensitivity,
         json.dumps(metadata or {})),
    ).fetchone()

    if row:
        return row["id"], True

    existing = conn.execute(
        "SELECT id FROM document WHERE content_hash = %s", (content_hash,)
    ).fetchone()
    return existing["id"], False


def insert_chunks(
    conn: psycopg.Connection,
    *,
    document_id: uuid.UUID,
    chunks: list,  # list[ingest.Chunk] — carries text + char offsets
    embeddings: list[list[float]],
    sensitivity: int,
) -> list[uuid.UUID]:
    """Write chunks + embeddings, preserving char offsets. Postgres mints the UUIDs
    the graph will reuse."""
    ids: list[uuid.UUID] = []
    for c, vector in zip(chunks, embeddings, strict=True):
        row = conn.execute(
            """
            INSERT INTO chunk (document_id, ordinal, text, start_char, end_char,
                               sensitivity, embedding)
            VALUES (%s, %s, %s, %s, %s, %s, %s)
            RETURNING id
            """,
            (document_id, c.ordinal, c.text, c.start_char, c.end_char, sensitivity, vector),
        ).fetchone()
        ids.append(row["id"])
    return ids


def queue_proposals(
    conn: psycopg.Connection,
    *,
    document_id: uuid.UUID,
    chunk_id: uuid.UUID,
    chunk_start: int,
    chunk_text: str,
    verified,  # extract.VerifiedExtraction
    stamp: dict[str, str],
) -> tuple[int, int]:
    """Park verified claims in the approval queue and quarantine the rejects.

    Returns (queued, quarantined). Nothing reaches the graph here.

    Evidence spans are converted from chunk-relative to document-absolute offsets, so
    a reviewer (or the frontend) can highlight the exact sentence in the original
    document rather than being handed a paragraph and told to go looking.
    """
    queued = 0

    for entity in verified.entities:
        conn.execute(
            """
            INSERT INTO proposed_change
                (document_id, chunk_id, kind, payload, confidence,
                 provider, extractor_model, prompt_version, ontology_version)
            VALUES (%s, %s, 'add_entity', %s, %s, %s, %s, %s, %s)
            """,
            (
                document_id,
                chunk_id,
                json.dumps({
                    "name": entity.name,
                    "type": entity.type.value,
                    "attributes": entity.attributes,
                    "chunk_id": str(chunk_id),
                }),
                # An entity that literally appears in the text is not a judgment call.
                # The judgment — and therefore the uncertainty — lives in the edges.
                1.0,
                stamp["provider"], stamp["extractor_model"],
                stamp["prompt_version"], stamp["ontology_version"],
            ),
        )
        queued += 1

    for i, rel in enumerate(verified.relationships):
        local = verified.spans.get(i)
        abs_start = chunk_start + local[0] if local else None
        abs_end = chunk_start + local[1] if local else None

        conn.execute(
            """
            INSERT INTO proposed_change
                (document_id, chunk_id, kind, payload, confidence,
                 quote, quote_start, quote_end,
                 provider, extractor_model, prompt_version, ontology_version)
            VALUES (%s, %s, 'add_relationship', %s, %s, %s, %s, %s, %s, %s, %s, %s)
            """,
            (
                document_id,
                chunk_id,
                json.dumps({
                    "source": rel.source,
                    "type": rel.type.value,
                    "target": rel.target,
                    "quote": rel.evidence,
                    "chunk_id": str(chunk_id),
                }),
                rel.confidence,
                rel.evidence,
                abs_start,
                abs_end,
                stamp["provider"], stamp["extractor_model"],
                stamp["prompt_version"], stamp["ontology_version"],
            ),
        )
        queued += 1

    for failure in verified.failures:
        conn.execute(
            """
            INSERT INTO extraction_failure
                (document_id, chunk_id, source, relation, target, quote, confidence,
                 reason, detail, provider, extractor_model, prompt_version,
                 ontology_version, chunk_chars)
            VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)
            """,
            (
                document_id, chunk_id,
                failure.source, failure.relation, failure.target,
                failure.quote, failure.confidence,
                failure.reason.value, failure.detail,
                stamp["provider"], stamp["extractor_model"],
                stamp["prompt_version"], stamp["ontology_version"],
                len(chunk_text),
            ),
        )

    return queued, len(verified.failures)


def failure_stats(conn: psycopg.Connection) -> list[dict[str, Any]]:
    """The quarantine, aggregated. This is the Phase 7 evaluation table in embryo:
    fabrication rate by model, by prompt version, by relation type."""
    return conn.execute(
        """
        SELECT extractor_model, prompt_version, relation, reason,
               count(*) AS n,
               round(avg(confidence)::numeric, 2) AS avg_claimed_confidence,
               round(avg(chunk_chars)::numeric) AS avg_chunk_chars
        FROM extraction_failure
        GROUP BY extractor_model, prompt_version, relation, reason
        ORDER BY n DESC
        """
    ).fetchall()


def pending(conn: psycopg.Connection, limit: int = 50) -> list[dict[str, Any]]:
    """The founder's review queue, lowest-confidence first — the ones most worth a human."""
    return conn.execute(
        """
        SELECT id, kind, payload, confidence, created_at
        FROM proposed_change
        WHERE status = 'pending'
        ORDER BY confidence ASC, created_at ASC
        LIMIT %s
        """,
        (limit,),
    ).fetchall()


def pending_entity_conflicts(
    conn: psycopg.Connection, *, clearance: int = 4, limit: int = 50
) -> list[dict[str, Any]]:
    """Entity name conflict review queue, filtered by the reviewer's clearance.

    Ordered by similarity descending — highest-confidence alias candidates first,
    because those are cheapest to confirm and most damaging if silently merged.
    """
    return conn.execute(
        """
        SELECT id, name_a, type_a, name_b, type_b,
               similarity, quote_a, quote_b, sensitivity, created_at
        FROM entity_conflict
        WHERE status = 'pending' AND sensitivity <= %s
        ORDER BY similarity DESC, created_at ASC
        LIMIT %s
        """,
        (clearance, limit),
    ).fetchall()


def conflict_stats(conn: psycopg.Connection) -> dict[str, int]:
    """Summary counts for the entity conflict queue (for doctor / status commands)."""
    row = conn.execute(
        """
        SELECT
            count(*) FILTER (WHERE status = 'pending')  AS pending,
            count(*) FILTER (WHERE status = 'approved') AS approved,
            count(*) FILTER (WHERE status = 'rejected') AS rejected
        FROM entity_conflict
        """
    ).fetchone()
    return dict(row) if row else {"pending": 0, "approved": 0, "rejected": 0}


# ---------------------------------------------------------------------------
# Neo4j
# ---------------------------------------------------------------------------


def neo(wait: float = 60.0) -> Driver:
    """Connect to Neo4j, waiting for it to come up if necessary.

    A fresh container takes 20-30s to accept Bolt connections; the driver itself
    does not retry the initial handshake. Without this, any command run right after
    `docker compose up` dies with a ConnectionReset mid-handshake.
    """
    import time

    from neo4j.exceptions import ServiceUnavailable

    cfg = settings()
    driver = GraphDatabase.driver(cfg.neo4j_uri, auth=(cfg.neo4j_user, cfg.neo4j_password))

    deadline = time.monotonic() + wait
    while True:
        try:
            driver.verify_connectivity()
            return driver
        except (ServiceUnavailable, OSError):
            if time.monotonic() >= deadline:
                raise
            time.sleep(2.0)


CONSTRAINTS = [
    "CREATE CONSTRAINT chunk_id IF NOT EXISTS FOR (c:Chunk) REQUIRE c.id IS UNIQUE",
    # Entities are identified by (name, type). Two people called "Raj" collapse into
    # one node — that is entity resolution by exact name, and it is the honest
    # limitation of this prototype. Real resolution (aliases, "Raj" vs "Rajesh Kumar",
    # embedding-similarity blocking) is scoped as future work; say so in the report
    # rather than pretending the problem does not exist.
    "CREATE CONSTRAINT entity_key IF NOT EXISTS FOR (e:Entity) REQUIRE (e.name, e.type) IS UNIQUE",
]


def ensure_constraints(driver: Driver) -> None:
    with driver.session() as session:
        for stmt in CONSTRAINTS:
            session.run(stmt)


def entity_names(driver: Driver) -> list[str]:
    """Every entity name in the graph.

    Evaluation seeding and administrative tooling may need the complete vocabulary. Runtime
    question planning must instead use :func:`entity_names_for_chunks`, which scopes the
    candidate list to source chunks already readable by the caller.
    """
    with driver.session() as session:
        result = session.run("MATCH (e:Entity) RETURN e.name AS name ORDER BY name")
        return [r["name"] for r in result]


def entity_names_for_chunks(
    driver: Driver, chunk_ids: list[uuid.UUID], clearance: int
) -> list[str]:
    """Return canonical names mentioned by readable candidate chunks only.

    A grounding prompt is a disclosure channel: sending it the whole graph vocabulary can
    reveal a confidential name. Candidate chunks come from a clearance-filtered vector
    query; this Cypher repeats the predicate so it fails closed for direct callers too.
    """
    if not chunk_ids:
        return []
    with driver.session() as session:
        result = session.run(
            """
            MATCH (c:Chunk)-[:MENTIONS]->(e:Entity)
            WHERE c.id IN $chunk_ids AND c.sensitivity <= $clearance
            RETURN DISTINCT e.name AS name
            ORDER BY name
            """,
            chunk_ids=[str(chunk_id) for chunk_id in set(chunk_ids)],
            clearance=clearance,
        )
        return [r["name"] for r in result]


def upsert_chunk_node(driver: Driver, *, chunk_id: uuid.UUID, document_id: uuid.UUID,
                      ordinal: int, sensitivity: int) -> None:
    """The graph half of the bridge. Text stays in Postgres; only the handle lives here."""
    with driver.session() as session:
        session.run(
            """
            MERGE (c:Chunk {id: $id})
            SET c.document_id = $document_id,
                c.ordinal     = $ordinal,
                c.sensitivity = $sensitivity
            """,
            id=str(chunk_id),
            document_id=str(document_id),
            ordinal=ordinal,
            sensitivity=sensitivity,
        )


def apply_entity(driver: Driver, payload: dict[str, Any]) -> None:
    """Commit an approved entity, and wire it to the chunk that mentions it."""
    with driver.session() as session:
        session.run(
            """
            MERGE (e:Entity {name: $name, type: $type})
            SET e += $attributes
            WITH e
            MATCH (c:Chunk {id: $chunk_id})
            MERGE (c)-[:MENTIONS]->(e)
            """,
            name=payload["name"],
            type=payload["type"],
            attributes=payload.get("attributes", {}),
            chunk_id=payload["chunk_id"],
        )


def apply_relationship(driver: Driver, payload: dict[str, Any]) -> None:
    """Commit an approved relationship.

    The edge type is interpolated into the Cypher string because Neo4j does not
    accept a parameterised relationship type. That is an injection surface, so the
    value is checked against the RelationType enum before it gets here — never
    relax that check, and never let an unvalidated string reach this function.
    """
    rel_type = payload["type"]
    from callosum.ontology import RelationType

    if rel_type not in RelationType.__members__.values():
        raise ValueError(f"Refusing to write unknown relationship type: {rel_type!r}")

    with driver.session() as session:
        session.run(
            f"""
            MATCH (s:Entity {{name: $source}})
            MATCH (t:Entity {{name: $target}})
            MERGE (s)-[r:{rel_type}]->(t)
            SET r.quote = $quote, r.chunk_id = $chunk_id
            """,
            source=payload["source"],
            target=payload["target"],
            quote=payload.get("quote", ""),
            chunk_id=payload["chunk_id"],
        )


def approve(conn: psycopg.Connection, driver: Driver, change_id: uuid.UUID,
            reviewer_id: uuid.UUID | None = None) -> None:
    """The only path by which anything reaches the graph.

    Postgres and Neo4j have no shared transaction, so we commit to the graph first
    and mark the row approved second. If the process dies between the two, the row
    stays 'pending' and gets re-applied — the graph writes are MERGE, so replaying
    is a no-op. The reverse order would risk a row marked approved whose edge was
    never written, which is the failure we cannot detect later.
    """
    row = conn.execute(
        "SELECT kind, payload FROM proposed_change WHERE id = %s AND status = 'pending'",
        (change_id,),
    ).fetchone()
    if not row:
        raise ValueError(f"No pending change {change_id}")

    if row["kind"] == "add_entity":
        apply_entity(driver, row["payload"])
    elif row["kind"] == "add_relationship":
        apply_relationship(driver, row["payload"])
    else:
        raise ValueError(f"Unknown change kind: {row['kind']}")

    conn.execute(
        """
        UPDATE proposed_change
        SET status = 'approved', reviewed_by = %s, reviewed_at = now()
        WHERE id = %s
        """,
        (reviewer_id, change_id),
    )

    conn.execute(
        """
        INSERT INTO node_version (node_id, node_label, version, properties, change_reason, created_by)
        VALUES (%s, %s,
                COALESCE((SELECT MAX(version) + 1 FROM node_version WHERE node_id = %s), 1),
                %s, 'approved from extraction', %s)
        """,
        (change_id, row["kind"], change_id, json.dumps(row["payload"]), reviewer_id),
    )
