/**
 * @jest-environment node
 *
 * The motion scale, made checkable.
 *
 * `DESIGN.md` published a motion hierarchy of two durations and one ease. The
 * code shipped five durations (0.12 / 0.2 / 0.35 / 1.1 / 150ms) and TWO rival
 * ease curves, and `session-gate.tsx` carried a comment saying its
 * `[0.22, 1, 0.36, 1]` "mirrors `--ease-out-quart`" — which is
 * `cubic-bezier(0.16, 1, 0.3, 1)`, so the claim was never true of the value
 * beneath it. Nothing was broken; the document simply described a system the
 * code did not have.
 *
 * That is the same shape of defect `palette-contrast.test.ts` was written for:
 * a generated-then-documented system left unguarded, drifting one commit at a
 * time while every test stayed green. This file is the motion equivalent.
 *
 * If an assertion here fails, do NOT relax it to match the code. Either the
 * component should be using a tier, or the scale genuinely needs a new one — in
 * which case declare it in `globals.css`, mirror it in `lib/motion.ts`, and
 * amend `DESIGN.md` under a date in the same commit.
 */

import { readdirSync, readFileSync, statSync } from "node:fs";
import { join } from "node:path";

import { DURATION, EASE, STAGGER } from "../src/lib/motion";

const SRC = join(__dirname, "..", "src");
const CSS = readFileSync(join(SRC, "app", "globals.css"), "utf8");

// --------------------------------------------------------------------------
// Parsing
// --------------------------------------------------------------------------

/** Every `@media (prefers-reduced-motion: reduce) { ... }` body, by brace matching. */
function reducedMotionBlocks(css: string): string[] {
  const out: string[] = [];
  const marker = "@media (prefers-reduced-motion: reduce)";
  let from = 0;
  for (;;) {
    const start = css.indexOf(marker, from);
    if (start === -1) return out;
    const open = css.indexOf("{", start);
    let depth = 0;
    for (let i = open; i < css.length; i++) {
      if (css[i] === "{") depth++;
      else if (css[i] === "}") {
        depth--;
        if (depth === 0) {
          out.push(css.slice(open + 1, i));
          from = i;
          break;
        }
      }
    }
    if (depth !== 0) throw new Error("unbalanced braces in a reduced-motion block");
  }
}

const REDUCED = reducedMotionBlocks(CSS);

/** The stylesheet with its reduced-motion blocks removed — the motion that actually plays. */
const CSS_PLAYING = REDUCED.reduce((acc, body) => acc.replace(body, ""), CSS);

/** `--name: value;` for one token, searched in the whole sheet. */
function token(name: string): string {
  const m = new RegExp(`--${name}\\s*:\\s*([^;]+);`).exec(CSS);
  if (!m) throw new Error(`token not declared in globals.css: --${name}`);
  return m[1].trim();
}

/** Comments carry prose about durations; they are not declarations. */
function stripComments(css: string): string {
  return css.replace(/\/\*[\s\S]*?\*\//g, "");
}

/**
 * The same, for TypeScript sources, plus `//` lines. Without this the assertions
 * below flag their own explanations: this file's rationale in `lib/motion.ts` and
 * `session-gate.tsx` both quote the ease they exist to have removed.
 */
function stripSourceComments(src: string): string {
  return src.replace(/\/\*[\s\S]*?\*\//g, "").replace(/^\s*\/\/.*$/gm, "");
}

/** Recursively collect `.ts`/`.tsx` under a directory. */
function sources(dir: string, acc: string[] = []): string[] {
  for (const entry of readdirSync(dir)) {
    const path = join(dir, entry);
    if (statSync(path).isDirectory()) {
      // `vendor/` is generated by `shadcn add` and rewritten by `retoken.mjs`.
      // DESIGN.md §5 already states it is not hand-maintained source; holding it
      // to a scale it never read would just mean editing files the CLI overwrites.
      if (entry === "vendor" || entry === "node_modules") continue;
      sources(path, acc);
    } else if (/\.tsx?$/.test(entry)) {
      acc.push(path);
    }
  }
  return acc;
}

const SOURCES = sources(SRC).filter((p) => !p.endsWith(join("lib", "motion.ts")));

// --------------------------------------------------------------------------

describe("the CSS scale and its JS mirror cannot drift apart", () => {
  /**
   * `lib/motion.ts` exists because Framer animates inline styles from JS and
   * cannot read a custom property. A mirror nothing checks is just a second
   * place to be wrong, so it is checked.
   */
  it.each(Object.keys(DURATION) as (keyof typeof DURATION)[])(
    "declares --duration-%s in globals.css with the same value",
    (tier) => {
      const declared = token(`duration-${tier}`);
      expect(declared).toMatch(/^\d+ms$/);
      expect(parseInt(declared, 10) / 1000).toBeCloseTo(DURATION[tier], 5);
    },
  );

  it("declares --stagger-step with the same value as STAGGER", () => {
    expect(parseInt(token("stagger-step"), 10) / 1000).toBeCloseTo(STAGGER, 5);
  });

  it("declares --ease-out-quart with the same four control points as EASE", () => {
    const declared = token("ease-out-quart");
    const args = /cubic-bezier\(([^)]*)\)/.exec(declared);
    expect(args).not.toBeNull();
    expect(args![1].split(",").map((n) => Number(n.trim()))).toEqual([...EASE]);
  });

  it("has no duration tier in globals.css that the mirror is missing", () => {
    const tiers = [...CSS.matchAll(/--duration-([a-z-]+)\s*:/g)].map((m) => m[1]);
    expect([...new Set(tiers)].sort()).toEqual(Object.keys(DURATION).sort());
  });
});

describe("globals.css names tiers, never numbers", () => {
  const declarations = stripComments(CSS_PLAYING).matchAll(
    /(transition|transition-duration|transition-delay|animation|animation-duration|animation-delay)\s*:\s*([^;]+);/g,
  );

  it("writes no literal time in any transition or animation declaration", () => {
    const literals: string[] = [];
    for (const [, prop, value] of declarations) {
      // `0s` and `0ms` are not a tier — they are the absence of one — but nothing
      // currently needs them, so they are not carved out until something does.
      for (const t of value.matchAll(/\b\d+(?:\.\d+)?m?s\b/g)) {
        literals.push(`${prop}: … ${t[0]} …`);
      }
    }
    expect(literals).toEqual([]);
  });

  it("loops nothing", () => {
    /**
     * A reveal earns one pass. A figure that keeps moving after it has been read
     * is asking for attention it has no further claim on — and an infinite
     * animation is the one kind `prefers-reduced-motion`'s duration collapse
     * makes *worse*, by turning a slow pulse into a strobe.
     *
     * Scoped to `globals.css`: Tailwind's `animate-spin` and `animate-pulse` are
     * loading indicators, where the loop IS the signal, and they stop when the
     * thing they report on finishes.
     */
    expect(stripComments(CSS_PLAYING)).not.toMatch(/\binfinite\b/);
  });
});

describe("every animation has a reduced-motion answer", () => {
  /**
   * The global rule at the bottom of `globals.css` collapses animation DURATION,
   * which is not an answer for a `both`-filled animation with a delay: the
   * element stays invisible for its delay and then pops in. Motion replaced by a
   * flash is worse than the motion. Each animating class must therefore appear
   * in a reduced-motion block, where it is switched off outright and lands on
   * the natural state its keyframes end at.
   */
  const animating = [...stripComments(CSS_PLAYING).matchAll(/\.([a-z][a-z0-9-]*)[^{}]*\{[^}]*?\banimation\s*:/g)].map(
    (m) => m[1],
  );

  it("finds the animating utilities it expects to be checking", () => {
    // A guard on the parser itself: a regex that silently matched nothing would
    // make every assertion below vacuously true.
    expect([...new Set(animating)].sort()).toEqual(["reveal-draw", "reveal-fade", "reveal-grow", "rise-in"]);
  });

  it("switches each of them off under prefers-reduced-motion", () => {
    const off = REDUCED.join("\n");
    const missing = [...new Set(animating)].filter((cls) => !new RegExp(`\\.${cls}\\b`).test(off));
    expect(missing).toEqual([]);
  });

  it("ends every keyframe sequence at the element's natural state", () => {
    /**
     * This is what makes switching an animation off safe rather than lossy. A
     * `to` frame that stopped at `opacity: 0.6` would render wrong for every
     * reduced-motion reader, and no screenshot review would catch it, because
     * the reviewer's machine animates.
     */
    const natural = /^(opacity:\s*1|transform:\s*none|transform:\s*scaleX\(1\)|stroke-dashoffset:\s*0)$/;
    const frames = [...CSS.matchAll(/@keyframes\s+([a-z-]+)\s*\{([\s\S]*?)\n\}/g)];
    expect(frames.length).toBeGreaterThan(0);

    const bad: string[] = [];
    for (const [, name, body] of frames) {
      const to = /\bto\s*\{([^}]*)\}/.exec(body);
      if (!to) {
        bad.push(`${name}: no 'to' frame`);
        continue;
      }
      for (const decl of to[1].split(";").map((d) => d.trim()).filter(Boolean)) {
        if (!natural.test(decl)) bad.push(`${name}: 'to' sets ${decl}`);
      }
    }
    expect(bad).toEqual([]);
  });
});

describe("no component writes a duration or an ease of its own", () => {
  it("has no Framer transition with a literal non-zero duration", () => {
    const offenders: string[] = [];
    for (const path of SOURCES) {
      const src = stripSourceComments(readFileSync(path, "utf8"));
      for (const m of src.matchAll(/\bduration:\s*([0-9.]+)/g)) {
        // `0` is the reduced-motion branch, which `transition()` produces itself
        // but which a call site is still allowed to state directly.
        if (Number(m[1]) !== 0) offenders.push(`${path.slice(SRC.length + 1)}: duration: ${m[1]}`);
      }
    }
    expect(offenders).toEqual([]);
  });

  it("has no cubic-bezier control points written into a component", () => {
    const offenders: string[] = [];
    for (const path of SOURCES) {
      const src = stripSourceComments(readFileSync(path, "utf8"));
      // Both spellings: the CSS function, and the four-number array Framer takes.
      for (const m of src.matchAll(/cubic-bezier\(|\[\s*[0-9.]+\s*,\s*[0-9.]+\s*,\s*[0-9.]+\s*,\s*[0-9.]+\s*\]\s*as const/g)) {
        offenders.push(`${path.slice(SRC.length + 1)}: ${m[0]}`);
      }
    }
    expect(offenders).toEqual([]);
  });

  it("has no literal Tailwind duration utility outside vendor/", () => {
    /**
     * The drift this missed for longest: seven files carried `duration-150`, a
     * hover tier that is not on the scale (L1 is 120ms), consistently enough to
     * look deliberate. They now read `duration-(--duration-hover)`.
     *
     * A `var()` reference is the point of the scale and is not flagged; only a
     * number, or an arbitrary time, is. `tailwind-var-syntax.test.ts` separately
     * holds those references to the spelling Tailwind v4 actually compiles.
     */
    const offenders: string[] = [];
    for (const path of SOURCES) {
      const src = stripSourceComments(readFileSync(path, "utf8"));
      for (const m of src.matchAll(/\bduration-(\d+\b|\[[^\]]*\d+m?s[^\]]*\])/g)) {
        offenders.push(`${path.slice(SRC.length + 1)}: ${m[0]}`);
      }
    }
    expect(offenders).toEqual([]);
  });
});
