"use client";

/**
 * The authorization demo: one request, two identities, a visibly different answer.
 *
 * WHAT IS AND IS NOT COMPUTED HERE
 * --------------------------------
 * Nothing on this page is derived. The document count is `pack.items.length` — the rows
 * the server chose to send — and the withheld count is `pack.withheld_items` verbatim.
 * No total is subtracted, no gap is counted, no number is hardcoded. If the API returns
 * different figures tomorrow, this page shows different figures.
 *
 * That matters more here than on an ordinary screen, because the whole claim of the demo
 * is that the numbers came from the server's authorization decision. A count computed in
 * the browser would prove nothing.
 *
 * `withheld_items` is rendered per its contract in `lib/packs.ts`: "Render it; do not
 * treat a non-zero value as an error state." Withheld is not missing — the pack is
 * telling you material exists that you may not read, which is the disclosure ADR-018
 * exists to make.
 *
 * WHERE THE PACK ID COMES FROM
 * ----------------------------
 * `NEXT_PUBLIC_DEMO_PACK_ID`. There is no fallback baked in: a wrong id silently
 * rendering someone else's pack is worse than a page that says it is unconfigured.
 * The seeded value on a freshly built demo database is
 * `6c43d827-f95f-4f24-9e2b-cac1413479e5`, measured on 2026-09-05 from
 * `scripts/seed_demo_board.py`'s "Board Meeting 14 — pack"; it is regenerated by every
 * fresh seed, so it belongs in deployment config and not in this file.
 */

import { useCallback, useEffect, useState } from "react";

import { loadFailedText } from "@/lib/error-text";
import { ApiError, apiGet } from "@/lib/http";
import { documentsApi, type Document } from "@/lib/documents";
import type { BoardPack } from "@/lib/packs";
import {
  listDemoIdentities,
  selectDemoIdentity,
  type DemoIdentity,
  type DemoIdentityOption,
} from "@/lib/demo";

const PACK_ID = process.env.NEXT_PUBLIC_DEMO_PACK_ID ?? "";

export default function DemoPage() {
  const [options, setOptions] = useState<DemoIdentityOption[] | null>(null);
  const [active, setActive] = useState<DemoIdentity | null>(null);
  const [pack, setPack] = useState<BoardPack | null>(null);
  const [titles, setTitles] = useState<Record<string, string>>({});
  const [error, setError] = useState<string | null>(null);
  const [busy, setBusy] = useState(false);

  useEffect(() => {
    listDemoIdentities().then(setOptions);
  }, []);

  const choose = useCallback(async (identity: DemoIdentity) => {
    setBusy(true);
    setError(null);
    try {
      await selectDemoIdentity(identity);
      // Re-read after switching. The page holds no cached authorization state, so the
      // only way to learn what this identity may see is to ask the server again.
      //
      // Titles are resolved separately because `board_pack_item` carries a
      // `document_id` and nothing else — the pack contract deliberately does not
      // denormalise a title onto the item (`lib/documents.ts`). `/documents` is
      // clearance-filtered by the same membership, so this resolves exactly the rows
      // this identity may read and silently resolves nothing for the rest.
      const [fresh, docs] = await Promise.all([
        apiGet<BoardPack>(`/packs/${PACK_ID}`),
        documentsApi.list(),
      ]);
      setTitles(Object.fromEntries(docs.map((d: Document) => [d.id, d.title])));
      setPack(fresh);
      setActive(identity);
    } catch (err) {
      setPack(null);
      setTitles({});
      // Surface the server's own refusal rather than a generic message: a 401 here
      // means the session did not take, and a 404 means the configured pack id is
      // wrong. Those need different fixes and should not read alike.
      setError(
        err instanceof ApiError
          ? loadFailedText("The pack", err)
          : "The pack could not be loaded.",
      );
    } finally {
      setBusy(false);
    }
  }, []);

  if (options === null) {
    return (
      <main className="mx-auto max-w-2xl p-8">
        <h1 className="text-2xl font-semibold">Demo selector unavailable</h1>
        <p className="mt-2 text-sm opacity-70">
          This build does not have the demo selector enabled.
        </p>
      </main>
    );
  }

  if (!PACK_ID) {
    return (
      <main className="mx-auto max-w-2xl p-8">
        <h1 className="text-2xl font-semibold">Demo pack not configured</h1>
        <p className="mt-2 text-sm opacity-70">
          Set <code>NEXT_PUBLIC_DEMO_PACK_ID</code> to the seeded Board Meeting 14 pack.
        </p>
      </main>
    );
  }

  return (
    <main className="mx-auto max-w-2xl p-8">
      <h1 className="text-2xl font-semibold">Who are you?</h1>
      <p className="mt-1 text-sm opacity-70">
        The same request, as different people. Nothing below is computed in your browser.
      </p>

      <div className="mt-4 flex flex-wrap gap-2">
        {options.map((o) => (
          <button
            key={o.symbol}
            type="button"
            disabled={busy}
            onClick={() => choose(o.symbol)}
            aria-pressed={active === o.symbol}
            className={`rounded-md border px-4 py-2 text-sm transition-colors disabled:opacity-50 ${
              active === o.symbol ? "border-current font-medium" : "opacity-70"
            }`}
          >
            {o.label}
          </button>
        ))}
      </div>

      {error && (
        <p role="alert" className="mt-6 text-sm">
          {error}
        </p>
      )}

      {pack && (
        <section className="mt-8" aria-live="polite">
          <h2 className="text-lg font-medium">{pack.title}</h2>

          <div className="mt-3 flex gap-8">
            <div>
              <div className="text-3xl tabular-nums">{pack.items.length}</div>
              <div className="text-xs uppercase tracking-wide opacity-60">
                {pack.items.length === 1 ? "document" : "documents"}
              </div>
            </div>
            <div>
              <div className="text-3xl tabular-nums">{pack.withheld_items}</div>
              <div className="text-xs uppercase tracking-wide opacity-60">withheld</div>
            </div>
          </div>

          {pack.withheld_items > 0 && (
            <p className="mt-3 text-sm opacity-80">
              {pack.withheld_items === 1
                ? "1 document exists in this pack that you may not read."
                : `${pack.withheld_items} documents exist in this pack that you may not read.`}{" "}
              Withheld is not missing — the pack is telling you it is incomplete for you.
            </p>
          )}

          <ul className="mt-5 space-y-1">
            {pack.items.map((item) => (
              <li key={item.id} className="text-sm">
                <span className="opacity-50 tabular-nums">{item.position}.</span>{" "}
                {titles[item.document_id] ?? item.document_id}
              </li>
            ))}
          </ul>
        </section>
      )}
    </main>
  );
}
