// Where institutional memory came from, derived from the graph itself.
//
// Deliberately a SEPARATE module: `graph.ts` is generated by
// `scripts/gen_graph_data.py`, so hand-written logic must not live there or a
// regeneration would eat it. Everything below is computed from the nodes and
// edges that file already carries — no second source of truth, and nothing to
// drift out of sync.

import {
  NODE_TYPE_LABEL,
  type GraphNodeType,
  type GraphView,
} from "./graph";

export type ProvenanceEntry = {
  /** Raw source filename, as recorded on every extracted node and edge. */
  document: string;
  /** Human label for the document. */
  label: string;
  /** What kind of source this is — board transcripts read differently to email. */
  kind: "Transcript" | "Forecast" | "Email" | "Review";
  /** Entities this document introduced that no earlier document had. */
  entities: number;
  /** Relationships extracted from it. */
  relationships: number;
  /** Entity types it contributed, largest first. */
  types: { type: GraphNodeType; label: string; count: number }[];
  /** Decisions first recorded here — the reason a board reads a document at all. */
  decisions: string[];
  /** Above the default clearance; withheld from lower-clearance callers. */
  restricted: boolean;
};

/** `board_meeting_12_transcript` -> `Board Meeting 12`. */
function labelFor(document: string): string {
  const stem = document
    .replace(/_transcript$/, "")
    .replace(/_CONFIDENTIAL$/, "")
    .replace(/^messy_/, "");
  return stem
    .split("_")
    .map((w) =>
      /^(fy\d+|arr|soc)$/i.test(w) ? w.toUpperCase() : w.charAt(0).toUpperCase() + w.slice(1)
    )
    .join(" ");
}

function kindFor(document: string): ProvenanceEntry["kind"] {
  if (document.includes("forecast")) return "Forecast";
  if (document.includes("email")) return "Email";
  if (document.includes("review")) return "Review";
  return "Transcript";
}

/**
 * Group the graph by source document, in ingestion order.
 *
 * Order comes from first appearance in the node list, which the generator emits
 * in `GOLD_GROUPS` order — the order the corpus was actually built in. An entity
 * is credited to the FIRST document that introduced it, so re-mentions do not
 * double-count and the totals reconcile with the graph.
 */
export function provenanceOf(view: GraphView): ProvenanceEntry[] {
  const order: string[] = [];
  const seen = new Set<string>();
  for (const n of view.nodes) {
    if (!seen.has(n.document)) {
      seen.add(n.document);
      order.push(n.document);
    }
  }
  for (const e of view.edges) {
    if (!seen.has(e.document)) {
      seen.add(e.document);
      order.push(e.document);
    }
  }

  return order.map((document) => {
    const nodes = view.nodes.filter((n) => n.document === document);
    const edges = view.edges.filter((e) => e.document === document);

    const counts = new Map<GraphNodeType, number>();
    for (const n of nodes) counts.set(n.type, (counts.get(n.type) ?? 0) + 1);

    return {
      document,
      label: labelFor(document),
      kind: kindFor(document),
      entities: nodes.length,
      relationships: edges.length,
      types: [...counts.entries()]
        .map(([type, count]) => ({ type, label: NODE_TYPE_LABEL[type], count }))
        .sort((a, b) => b.count - a.count || a.label.localeCompare(b.label)),
      decisions: nodes.filter((n) => n.type === "Decision").map((n) => n.label),
      restricted: nodes.some((n) => n.restricted) || edges.some((e) => e.restricted),
    };
  });
}
